# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('time', models.TimeField(blank=True, default=datetime.date.today, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='login.User')),
            ],
        ),
    ]
