# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
